#!/bin/bash
#
# build-vocab.sh — Generate LPC vocabulary from corpus for all English voices
#
# Extracts every unique word from corpus.js, synthesises with each English
# macOS voice, encodes to TMS5220 LPC, and outputs a JS module per voice
# plus a combined module that randomly selects between voices per word.
#
# Prerequisites:
#   brew install ffmpeg
#   pip install python-wizard
#
# Usage:
#   ./scripts/build-vocab.sh
#
# Output:
#   lib/vocab-data.js — Combined vocab (all voices, random selection per word)
#   build/voices/     — Individual per-voice JS files (for inspection)
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TMP_DIR="/tmp/esea-vocab-build"
BUILD_DIR="$PROJECT_DIR/build/voices"
OUTPUT_FILE="$PROJECT_DIR/lib/vocab-data.js"

# python_wizard binary (from venv)
PYWIZARD="/tmp/esea-venv/bin/python_wizard"

# Minimum word length to encode
MIN_WORD_LENGTH=2

# English voices to encode
VOICES=(
  "Daniel"
  "Samantha"
  "Whisper"
)

# Minimum word length to encode
MIN_WORD_LENGTH=2

echo "=== ESEA Installation — Multi-Voice LPC Vocabulary Builder ==="
echo ""
echo "Voices: ${#VOICES[@]} English voices"
echo ""

# --- Check dependencies ---
if ! command -v say &>/dev/null; then
  echo "ERROR: 'say' not found. This script requires macOS."
  exit 1
fi

if ! command -v ffmpeg &>/dev/null; then
  echo "ERROR: 'ffmpeg' not found. Install with: brew install ffmpeg"
  exit 1
fi

if [[ ! -x "$PYWIZARD" ]]; then
  echo "ERROR: python_wizard not found at $PYWIZARD"
  echo "Setup with:"
  echo "  python3 -m venv /tmp/esea-venv"
  echo "  cd /tmp && git clone https://github.com/ptwz/python_wizard.git"
  echo "  cd /tmp/python_wizard && /tmp/esea-venv/bin/pip install ."
  exit 1
fi

# --- Setup ---
rm -rf "$TMP_DIR"
mkdir -p "$TMP_DIR/combined"
mkdir -p "$BUILD_DIR"

# --- Extract unique words from corpus ---
echo "Extracting words from corpus.js..."

node -e "
const fs = require('fs');
const src = fs.readFileSync('$PROJECT_DIR/corpus.js', 'utf8');

const match = src.match(/CORPUS\s*=\s*\[([\s\S]*)\]/);
if (!match) { console.error('Could not parse CORPUS'); process.exit(1); }

const corpus = eval('[' + match[1] + ']');

const words = [...new Set(
  corpus.join(' ')
    .toLowerCase()
    .replace(/[^a-z\s'-]/g, '')
    .split(/\s+/)
    .filter(w => w.length >= $MIN_WORD_LENGTH)
    .map(w => w.replace(/^['-]+|['-]+$/g, ''))
    .filter(w => w.length >= $MIN_WORD_LENGTH)
)].sort();

words.forEach(w => console.log(w));
" > "$TMP_DIR/words.txt"

TOTAL_WORDS=$(wc -l < "$TMP_DIR/words.txt" | tr -d ' ')
echo "Found $TOTAL_WORDS unique words to encode"
echo ""

# --- Process each voice ---
encode_word() {
  local word="$1"
  local voice="$2"
  local voice_dir="$3"
  local safe_name
  safe_name=$(echo "$word" | tr "'" "_" | tr " " "_")

  local aiff_file="$voice_dir/aiff/${safe_name}.aiff"
  local wav_file="$voice_dir/wav/${safe_name}.wav"

  # Generate audio
  if ! say -v "$voice" -o "$aiff_file" "$word" 2>/dev/null; then
    return 1
  fi

  # Convert to 8kHz mono WAV
  if ! ffmpeg -y -i "$aiff_file" -ar 8000 -ac 1 -sample_fmt s16 "$wav_file" -loglevel error 2>/dev/null; then
    return 1
  fi

  # Encode to LPC
  local lpc_output
  lpc_output=$("$PYWIZARD" "$wav_file" -S -T tms5220 -f arduino 2>/dev/null || true)

  if [[ -z "$lpc_output" ]]; then
    return 1
  fi

  # Extract byte array
  local bytes
  bytes=$(echo "$lpc_output" | grep -o '{[^}]*}' | tr -d '{}' | tr -d ' ')

  if [[ -z "$bytes" ]]; then
    bytes=$(echo "$lpc_output" | grep -o '0x[0-9A-Fa-f,x ]*' | tr -d ' ' | head -1)
  fi

  if [[ -z "$bytes" ]]; then
    return 1
  fi

  echo "$bytes"
  return 0
}

VOICE_COUNT=0

for voice in "${VOICES[@]}"; do
  VOICE_SAFE=$(echo "$voice" | tr " ()" "_" | tr -d "'\"")
  VOICE_DIR="$TMP_DIR/$VOICE_SAFE"
  mkdir -p "$VOICE_DIR/aiff" "$VOICE_DIR/wav"

  echo "--- Voice: $voice ---"

  VOICE_FILE="$BUILD_DIR/${VOICE_SAFE}.js"
  SUCCEEDED=0
  FAILED=0

  # Start per-voice file
  echo "// Voice: $voice" > "$VOICE_FILE"
  echo "// Auto-generated by scripts/build-vocab.sh" >> "$VOICE_FILE"
  echo "export default {" >> "$VOICE_FILE"

  while IFS= read -r word; do
    BYTES=$(encode_word "$word" "$voice" "$VOICE_DIR" 2>/dev/null || true)

    if [[ -n "$BYTES" ]]; then
      echo "  '${word}': [${BYTES}]," >> "$VOICE_FILE"
      SUCCEEDED=$((SUCCEEDED + 1))

      # Store for combined output: append to a file per word
      echo "${VOICE_COUNT}|${BYTES}" >> "$TMP_DIR/combined/${word}.txt"
    else
      FAILED=$((FAILED + 1))
    fi
  done < "$TMP_DIR/words.txt"

  echo "};" >> "$VOICE_FILE"

  echo "  Encoded: $SUCCEEDED / $TOTAL_WORDS (failed: $FAILED)"
  echo ""

  # Clean up audio files to save disk space
  rm -rf "$VOICE_DIR/aiff" "$VOICE_DIR/wav"

  VOICE_COUNT=$((VOICE_COUNT + 1))
done

# --- Build combined vocab (multiple pronunciations per word) ---
echo "=== Building combined vocabulary ==="

# Re-read results and build the combined JS file
cat > "$OUTPUT_FILE" << HEADER
/**
 * LPC Vocabulary Data — auto-generated by scripts/build-vocab.sh
 *
 * Each word has multiple pronunciations from different macOS voices,
 * all encoded as TMS5220-compatible LPC bitstreams.
 *
 * Voices used: ${#VOICES[@]} English voices
 * Words encoded: $TOTAL_WORDS from corpus.js
 *
 * Structure: VOCAB[word] = [[bytes], [bytes], ...] (array of variants)
 * The synthesiser picks a random variant each time a word is spoken.
 */

const VOCAB = {
HEADER

while IFS= read -r word; do
  COMBINED_FILE="$TMP_DIR/combined/${word}.txt"

  if [[ -f "$COMBINED_FILE" ]]; then
    # Read all variants for this word
    echo -n "  '${word}': [" >> "$OUTPUT_FILE"

    FIRST=true
    while IFS='|' read -r voice_idx bytes; do
      if [[ "$FIRST" == "true" ]]; then
        FIRST=false
      else
        echo -n "," >> "$OUTPUT_FILE"
      fi
      echo -n "[${bytes}]" >> "$OUTPUT_FILE"
    done < "$COMBINED_FILE"

    echo "]," >> "$OUTPUT_FILE"
  fi
done < "$TMP_DIR/words.txt"

cat >> "$OUTPUT_FILE" << 'FOOTER'
};

export default VOCAB;
export { VOCAB };
FOOTER

echo ""
echo "=== Done ==="
echo "  Voices processed: $VOICE_COUNT"
echo "  Words per voice:  $TOTAL_WORDS"
echo "  Combined output:  $OUTPUT_FILE"
echo "  Per-voice files:  $BUILD_DIR/"
echo ""
echo "The combined VOCAB stores multiple pronunciations per word."
echo "Update formant-synth.js to pick a random variant when speaking."
